version: '3.8'

services:
  app:
    container_name: quarkus-couch-idp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    volumes_from:
      - couchdb:rw
    ports:
      - 8091:8080
    environment:
      - MAVEN_OPTS=-Dquarkus.http.host=0.0.0.0=value
    command: sleep infinity
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:latest
    container_name: couchdb-idp
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - 5984:5984
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-idp
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8090:8080
    restart: unless-stopped
    depends_on:
      - couchdb
    command: start-dev
