on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  house-keeping:
    runs-on: ubuntu-latest
    steps:
      - name: Limit to last 10 containers
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'couchdb-idp-updater'
          package-type: 'container'
          min-versions-to-keep: 10
          token: ${{ secrets.GIT_NPM_PACKAGES }}
